version: '3.8'
services:
  api:
    build:
      context: '..'
      dockerfile: 'Dockerfile'
    networks:
      - webproxy
    env_file: .env
    ports:
      - '3000:3000'
  sql:
    image: 'postgres:14'
    networks:
      - webproxy
    env_file:
      - .env
    ports:
      - 5432:5432
  redis:
    image: 'redis:6'
    networks:
      - webproxy
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    ports:
      - 6379:6379
networks:
  webproxy:
    driver: bridge
