type DaoPersonalizedData {
  followed: Boolean!
}

type DAO {
  id: ID!
  snapshotId: ID!
  name: String!
  logo: String
  overview: String!
  tokenOverview: String!

  tokens(onlyMain: Boolean): [Token!]
  personalizedData: DaoPersonalizedData
}
