type Proposal {
  id: ID!
  title: String!
  dao: DAO!
  juniorDescription: String!
  middleDescription: String!
  seniorDescription: String!
  # UNIX Timestamp (in ms)
  startAt: Int!
  # UNIX Timestamp (in ms)
  endAt: Int!
  author: String!
  totalVoters: Int!
}
