type Wallet {
  id: ID!
  address: String!
  ens: String
  tokens: [Token!]!
}

type User {
  id: ID!
  walletAddress: String! @deprecated(reason: "wallet object has required address parameter")
  wallet: Wallet! @deprecated(reason: "user has multiple wallets, this parameter returns random wallet")
  wallets: [Wallet!]!
  followedDaos: [DAO!]!
  avatarUrl: String!
}
