type Query {
  me: User!

  proposals(daoIds: [ID!], onlyFollowedDaos: Boolean): [Proposal!]! @deprecated(reason: "Lacks pagination. Use `proposalsV2`")
  proposalsV2(first: Int, after: String, daoIds: [ID!], onlyFollowedDaos: Boolean): ProposalConnection!

  daos(ids: [ID!], onlyFollowed: Boolean): [DAO!]! @deprecated(reason: "Lacks pagination. Use `daosV2`")
  daosV2(first: Int, after: String, ids: [ID!], onlyFollowed: Boolean): DAOConnection!
}

type Mutation {
  registerUser(walletAddress: ID!): User!

  followDao(daoId: ID!): DAO!
  unfollowDao(daoId: ID!): DAO!
}
